modules:
  enable::
      - tcl
  tcl:
    all:
      suffixes:
          '+mpi': 'mpi'
          '^python@3': 'python3'
          '^python@2.7': 'python2'
          '+shared': 'shared'
      autoload: 'direct'
      conflict:
          - '${PACKAGE}'
    hash_length: 0
    naming_scheme: '${PACKAGE}/${VERSION}-${COMPILERNAME}'
    blacklist: ['autoconf', 'libtool', 'pkg-config', 'automake', 'flex', 'bison', 'ncurses']
